# Load a bunch of annoying constants

In [ ]:
from pathlib import Path
import polars as pl
import numpy as np
from dataclasses import dataclass
import json
from typing import Dict, Any


COMPOUND_CONTROLS: set[str] = {
    "REC-0000058",
    "REC-0000069",
    "REC-0000098",
    "REC-0000219",
    "REC-0000370",
    "REC-0000375",
    "REC-0000391",
    "REC-0000493",
    "REC-0000584",
    "REC-0000590",
    "REC-0000671",
    "REC-0000706",
    "REC-0000737",
    "REC-0000741",
    "REC-0000773",
    "REC-0000842",
    "REC-0000854",
    "REC-0000867",
    "REC-0000889",
    "REC-0000959",
    "REC-0000970",
    "REC-0001029",
    "REC-0001106",
    "REC-0001148",
    "REC-0001183",
    "REC-0001214",
    "REC-0001246",
    "REC-0001249",
    "REC-0001250",
    "REC-0001258",
    "REC-0001289",
    "REC-0001290",
    "REC-0001610",
    "REC-0001619",
    "REC-0001655",
    "REC-0001721",
    "REC-0001730",
    "REC-0001744",
    "REC-0001907",
    "REC-0002007",
    "REC-0002082",
    "REC-0002101",
    "REC-0002178",
    "REC-0003420",
    "REC-0003935",
    "REC-0003980",
    "REC-0003982",
    "REC-0004011",
    "REC-0004273",
    "REC-0004419",
}

NEGATIVE_CONTROLS = [
    "REC-GRNA-0009335",
    "REC-GRNA-0010053",
    "REC-GRNA-0010043",
    "REC-GRNA-0010071",
    "REC-GRNA-0009367",
    "REC-GRNA-0014046",
    "REC-GRNA-0010050",
    "REC-GRNA-0009413",
    "REC-GRNA-0009427",
    "REC-GRNA-0010039",
    "REC-GRNA-0010038",
    "REC-GRNA-0014049",
    "REC-GRNA-0010063",
    "REC-GRNA-0009337",
    "REC-GRNA-0010048",
    "REC-GRNA-0014047",
    "REC-GRNA-0010069",
    "REC-GRNA-0014051",
    "REC-GRNA-0014042",
    "REC-GRNA-0010036",
    "REC-GRNA-0014045",
    "REC-GRNA-0010044",
    "REC-GRNA-0010049",
    "REC-GRNA-0010056",
    "REC-GRNA-0010051",
    "REC-GRNA-0014052",
    "REC-GRNA-0009319",
    "REC-GRNA-0014050",
    "REC-GRNA-0009481",
    "REC-GRNA-0010054",
    "REC-GRNA-0014044",
    "REC-GRNA-0014048",
    "REC-GRNA-0014043",
    "REC-GRNA-0009383",
    "REC-GRNA-0009435",
    "REC-GRNA-0010066",
    "REC-GRNA-0009345",
    "REC-GRNA-0010041",
    "REC-GRNA-0010065",
    "REC-GRNA-0010052",
    "REC-GRNA-0009329",
    "REC-GRNA-0010068",
    "REC-GRNA-0010040",
    "REC-GRNA-0009503",
    "REC-GRNA-0010046",
    ### SIRNA
    "REC-SIRNA-047139",
    "REC-SIRNA-046347",
    "REC-SIRNA-023618",
    "REC-SIRNA-011891",
    "REC-SIRNA-070391",
    "REC-SIRNA-033322",
    "REC-SIRNA-059857",
    "REC-SIRNA-055380",
    "REC-SIRNA-013118",
    "REC-SIRNA-069541",
    "REC-SIRNA-041233",
    "REC-SIRNA-010840",
    "REC-SIRNA-040984",
    "REC-SIRNA-052968",
    "REC-SIRNA-067904",
    "REC-SIRNA-055333",
    "REC-SIRNA-048898",
    "REC-SIRNA-013779",
    "REC-SIRNA-056649",
    "REC-SIRNA-000616",
    "REC-SIRNA-021198",
    "REC-SIRNA-043501",
    "REC-SIRNA-058443",
    "REC-SIRNA-036731",
    "REC-SIRNA-062542",
    "REC-SIRNA-032472",
    "REC-SIRNA-059495",
    "REC-SIRNA-059760",
    "REC-SIRNA-016146",
    "REC-SIRNA-038275",
    "REC-SIRNA-069619",
    "REC-SIRNA-013244",
    "REC-SIRNA-042015",
    "REC-SIRNA-012441",
    "REC-SIRNA-006388",
    "REC-SIRNA-055947",
    "REC-SIRNA-035097",
    "REC-SIRNA-061483",
    "REC-SIRNA-038396",
    "REC-SIRNA-035423",
    "REC-SIRNA-028005",
    "REC-SIRNA-008605",
    "REC-SIRNA-038221",
    "REC-SIRNA-016879",
    "REC-SIRNA-039836",
    "REC-SIRNA-004205",
    "REC-SIRNA-055086",
    "REC-SIRNA-061270",
    "REC-SIRNA-012679",
    "REC-SIRNA-042894",
    "REC-SIRNA-042662",
    "REC-SIRNA-027850",
    "REC-SIRNA-063815",
    "REC-SIRNA-025061",
    "REC-SIRNA-067581",
    "REC-SIRNA-041265",
    "REC-SIRNA-000791",
    "REC-SIRNA-028754",
    "REC-SIRNA-047032",
    "REC-SIRNA-021964",
    "REC-SIRNA-037754",
    "REC-SIRNA-039652",
    "REC-SIRNA-037864",
]


class Tokenizer:
    def __init__(self):
        self.token_to_id = {}
        self.id_to_token = []

    def fit(self, df: pl.Series):
        unique_tokens: pl.Series = df.sort()
        for i, token in enumerate(unique_tokens):
            self.token_to_id[token] = i
            self.id_to_token.append(token)
        return self

    def transform(self, x):
        if isinstance(x, str):
            x = [x]
        return [self.token_to_id[token] for token in np.array(x).flatten()]
    
    def __len__(self):
        return len(self.id_to_token)

    def __call__(self, x):
        return self.transform(x)


CROSS_CELL_LINE_BASE_PATH = Path(
    "/rxrx/data/valence/phenomics/cross_cell_line__brightfield__pretrain__v1_1" # v1_0 or v1_1
)

RESERVATION_PATH = Path(
    "/rxrx/data/valence/internal_benchmarking/vcds1/v1_3_reservation.json"
)

CASE_STUDY_MOLECULES = Path("/rxrx/data/user/ali.denton/outgoing/candidates_for_case_studies.csv")

CROSS_CELL_LINE_OBS_PATH: Path = (
    CROSS_CELL_LINE_BASE_PATH
    / "cross_cell_line__brightfield__pretrain__v1_1_obs.parquet"
)
INTERNAL_BENCHMARKING_BASE_PATH = Path("/rxrx/data/valence/internal_benchmarking/")


DRUGSCREEN_OBS_PATH: Path = (
    INTERNAL_BENCHMARKING_BASE_PATH
    / "vcds1"
    / "drugscreen__cell_paint__v1_2"
    / "drugscreen__cell_paint__v1_2_obs.parquet"
)
CROSS_CELL_LINE_TEST_OBS_PATH: Path = (
    INTERNAL_BENCHMARKING_BASE_PATH
    / "vcds1"
    / "cross_cell_line__brightfield__v1_1"
    / "cross_cell_line__brightfield__v1_1_obs.parquet"
)

# COMMON_COLUMNS: list[str] = [
#     "path",
#     "assay_type",
#     "shape",
#     "source",
#     "assay_type_id",
#     "experiment",
#     "experiment_id",
#     "cell_condition",
#     "cell_condition_id",
#     "comp_id",
#     "c_concs",
# ]

COMPOUND_PATTERN = r"^REC-\d+$"
TARGET_WELLS = 1000
TRAIN_FRACTION = 0.9
METADATA_SPLIT_SEED = 123456
OBS_SPLIT_SEED = 123456789


# def assign_random_split(
#     df: pl.DataFrame, train_fraction: float, seed: int
# ) -> pl.DataFrame:
#     """Assign a reproducible train/val split."""
#     n_train = int(df.height * train_fraction)
#     return df.with_columns(
#         pl.when(pl.int_range(0, pl.len()).shuffle(seed=seed) < n_train)
#         .then(pl.lit("train"))
#         .otherwise(pl.lit("val"))
#         .alias("split")
#     )

# Images with zarrs that are known to be corrupted
SKIP_IMAGES: list[str] = pl.read_csv(
    "/mnt/ps/home/CORP/jason.hartford/project/big-x/joint-model/metadata/zarr_scan_shards/skip_paths_all.csv"
)["path"].to_list()

@dataclass(frozen=True)
class SplitIndices:
    finetune: np.ndarray
    validation: np.ndarray
    test: np.ndarray

def load_vcb_split_indices(splits_path: Path) -> tuple[Dict[str, Any], SplitIndices]:
    """Load finetune/validation/test split indices."""
    with splits_path.open() as handle:
        splits_json = json.load(handle)
    first_fold = splits_json["folds"][0]
    split_indices = SplitIndices(
        finetune=np.array(first_fold["finetune"]),
        validation=np.array(first_fold["validation"]),
        test=np.array(first_fold["test"]),
    )
    return splits_json, split_indices

# Load the DRUGSCREEN splits
SPLITS_PATH: Path = (
    INTERNAL_BENCHMARKING_BASE_PATH
    / "vcb"
    / "splits"
    / "drugscreen__cell_paint__v1_2"
    / "split_compound_random__v1.json"
)
_, vcb_splits = load_vcb_split_indices(SPLITS_PATH)

CROSS_CELL_LINE_SPLITS_PATH: Path = (
    INTERNAL_BENCHMARKING_BASE_PATH
    / "vcb"
    / "splits"
    / "cross_cell_line__brightfield__v1_1"
    / "split_cell_type_manual__v1.json"
)

_, cross_cell_line_splits = load_vcb_split_indices(CROSS_CELL_LINE_SPLITS_PATH)

# Tx Data

In [ ]:
import zarr
import torch
import sys
sys.path.append("/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img")
from dataset import DataFrameTokenizer

obs = pl.read_parquet("/rxrx/data/user/ali.denton/tmp/training_trek__v1_0/training_trek__v1_0_obs.parquet")
obs = obs.with_row_index("zarr_row_idx").with_columns(
        pl.lit("trek").alias("assay_type"),
        pl.lit("training_trek__v1_0").alias("source"),
        pl.lit(None).alias("shape"),
        pl.lit("train").alias("split"),
        rec_id=pl.col("perturbations").list.eval(
            pl.element().struct.field("source_id")
        ),
        concentration=pl.col("perturbations").list.eval(
            pl.element().struct.field("concentration").cast(pl.Float64).cast(pl.String)
        ),
    )

lookup_df = (
    obs.group_by("batch_center")
    .agg([
        pl.col("zarr_row_idx").alias("all_indices"),
        # Optional: specific lookup for negative controls
        pl.col("zarr_row_idx").filter(pl.col("is_negative_control")).alias("control_indices")
    ])
)
control_map = dict(zip(lookup_df["batch_center"], 
                            lookup_df["control_indices"]))

row = obs.row(1235, named=True)
control = obs.row(control_map[row['batch_center']].sample(1).item(), named=True)
rec_id_tokenizer = Tokenizer().fit(obs['rec_id'].explode().unique())
concentration_tokenizer = Tokenizer().fit(obs['concentration'].explode().unique())
cell_type_tokenizer = Tokenizer().fit(obs['cell_type'].unique())
assay_type_tokenizer = Tokenizer().fit(obs['assay_type'].unique())
experiment_tokenizer = Tokenizer().fit(obs['experiment_label'].unique())

print("Unique rec_ids: ", len(rec_id_tokenizer))
print("Unique concentrations: ", len(concentration_tokenizer))
print("Unique cell_types: ", len(cell_type_tokenizer))
print("Unique assay_types: ", len(assay_type_tokenizer))
print("Unique experiments: ", len(experiment_tokenizer))


# Example Dataloader
class CellDataset(torch.utils.data.Dataset):
    def __init__(
        self,
        metadata: pl.DataFrame,
        tokenizer: DataFrameTokenizer,
        train: bool,
        size: int,
        multiscale: bool = False,
    ):
        required_cols = [
            "image_path",
            "cell_type",
            "experiment_label",
            "assay_type",
            "well_address",
            "rec_id",
            "concentration",
        ]
        assert all(col in metadata.columns for col in required_cols), (
            f"metadata must have the following columns: {required_cols}"
        )
        self.metadata = metadata
        self.train = train
        self.tokenizer = tokenizer
        self.zarr_file = zarr.open(zarr_path)

    def __len__(self):
        return len(self.metadata)

    def __getitem__(self, index: int):
        row = self.metadata.row(index, named=True)
        control = obs.row(control_map[row['batch_center']].sample(1).item(), named=True)
        tx = torch.from_numpy(self.zarr_file[row["zarr_row_idx"]])
        tx_control = torch.from_numpy(self.zarr_file[control["zarr_row_idx"]])
        sample = {
            "tx": tx,
            "tx_control": tx_control,
            "meta": self.tokenizer(row),
        }
        return sample

/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/.venv/lib/python3.13/site-packages/torch/amp/autocast_mode.py:270: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(

Unique rec_ids:  6469
Unique concentrations:  34
Unique cell_types:  8
Unique image_types:  1
Unique experiments:  809

# Load Recursion Data

In [ ]:
df: pl.DataFrame = pl.read_parquet('/rxrx/data/microscopy/photosynthetic_metadata/95M_filtered_6chan_rp006.parquet')
old_shape: tuple[int, int] = df.shape
print(f"Original shape: {old_shape}")
df: pl.DataFrame = df.filter(~pl.col("path").is_null())
new_shape: tuple[int, int] = df.shape
print(f"Dropped {old_shape[0] - new_shape[0]} rows with null paths")
old_shape = new_shape
df = df.filter(pl.col("shape") != [973, 973, 6])
df = df.filter(pl.col("shape") != [2510, 2510, 6])
df = df.filter(pl.col("shape") != [256, 256, 6])
df = df.filter(pl.col("shape") != [5120, 5120, 6])
df.rename({"image_type": "assay_type"})
new_shape = df.shape
print(f"Dropped {old_shape[0] - new_shape[0]} rows with weird shapes")
print(f"New shape: {new_shape}")

name1 = "bf_huvec_whole_genome_no_empty_v0.parquet"
name2 = "rptec_metadata_041625_no_96hr_no_empty.parquet"
base_path = "/rxrx/data/microscopy/photosynthetic_metadata/"
df_bf1 = pl.read_parquet(f"{base_path}{name1}")
df_bf2 = pl.read_parquet(f"{base_path}{name2}")
cols = list(set(df_bf1.columns).intersection(set(df_bf2.columns)))
df_bf = pl.concat([df_bf1[cols], df_bf2[cols]])

df_bf = df_bf.with_columns(
    pl.lit(False).alias("is_rp006"),
    pl.lit("brightfield_3channel").alias("assay_type"),
    pl.lit([2048, 2048, 3]).alias("shape"),
)
sorted_cols = sorted(df_bf.columns)
df = pl.concat([df_bf[sorted_cols], df[sorted_cols]])
new_shape = df.shape
print(f"New shape: {new_shape}")
print(f"Added {df.shape[0] - old_shape[0]} rows from brightfield metadata")
df = df.with_columns(split=pl.lit("train")) # make everything train for now.

# Match things up with VCB data

df = df.rename({
        "path": "image_path",
        "experiment": "experiment_label",
        "address": "well_address"
    })

df = df.with_columns(
    concentration=pl.col("concentration") * 1000
)

Original shape: (92764542, 20)
Dropped 0 rows with null paths
Dropped 425822 rows with weird shapes
New shape: (92338720, 20)
New shape: (108070006, 20)
Added 15305464 rows from brightfield metadata

In [3]:
df['shape'].value_counts()

shape: (3, 2)
┌─────────────────┬──────────┐
│ shape           ┆ count    │
│ ---             ┆ ---      │
│ list[i64]       ┆ u32      │
╞═════════════════╪══════════╡
│ [1024, 1024, 6] ┆ 33046574 │
│ [2048, 2048, 6] ┆ 59292146 │
│ [2048, 2048, 3] ┆ 15731286 │
└─────────────────┴──────────┘

In [5]:
# dropping reserved experiments and rec_ids from benchmarking team 

with open(RESERVATION_PATH) as f:
    reserved = json.load(f)

reserved_experiments = set(reserved["plated_rxrx_labels"])
reserved_rec_ids = set(reserved["rec_ids"])

num_to_drop = df.filter( (pl.col("experiment_label").is_in(reserved_experiments)))
print(f"Dropping {num_to_drop.shape[0]} rows with reserved experiments")
df = df.filter(~pl.col("experiment_label").is_in(reserved_experiments))

num_to_drop = df.filter( (pl.col("rec_id").list.set_intersection(list(reserved_rec_ids)).list.len() > 0))
print(f"Dropping {num_to_drop.shape[0]} rows with reserved rec_ids")
df = df.filter(~pl.col("rec_id").list.set_intersection(list(reserved_rec_ids)).list.len() > 0)

print(f"Remaining rows: {df.shape[0]:,}")

Dropping 11083704 rows with reserved experiments
Dropping 2034480 rows with reserved rec_ids
Remaining rows: 96,986,302

In [15]:
print(RESERVATION_PATH)

/rxrx/data/valence/internal_benchmarking/vcds1/v1_3_reservation.json

In [16]:
import polars as pl

def get_held_out_rec_ids(df, cell_type, sample_fraction=0.1):
    """
    Samples unique individual IDs (atoms) from the rec_id lists 
    for a specific cell type.
    """
    return (
        df.filter(pl.col('cell_type') == cell_type)
          .select(pl.col('rec_id'))
          .explode(pl.col('rec_id'))  # Flatten ['A', 'B'] into 'A', 'B'
          .unique(maintain_order=True)                   # Get unique pool of rec_ids
          .sample(fraction=sample_fraction, shuffle=True, seed=12345)
          .to_series()
          .to_list()                  # Return as Python list for use in filters
    )

# 1. Get the list of individual IDs (genes/compounds) to strictly hold out
arpe_held_out = get_held_out_rec_ids(df, 'ARPE19')
pl.DataFrame(arpe_held_out).write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/metadata/arpe_held_out.parquet')
rptec_held_out = get_held_out_rec_ids(df, 'RPTEC')
pl.DataFrame(rptec_held_out).write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/metadata/rptec_held_out.parquet')
huvec_held_out = get_held_out_rec_ids(df, 'HUVEC_TNFalpha')
pl.DataFrame(huvec_held_out).write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/metadata/huvec_held_out.parquet')

# 2. Assign split based on overlap (intersection)
# If a row contains ANY held-out ID, it goes to validation.
df = df.with_columns(
    pl.when(
        (pl.col("cell_type") == 'ARPE19') & 
        (pl.col("rec_id").list.set_intersection(arpe_held_out).list.len() > 0)
    ).then(pl.lit("valid_arpe19"))
    
    .when(
        (pl.col("cell_type") == 'RPTEC') & 
        (pl.col("rec_id").list.set_intersection(rptec_held_out).list.len() > 0)
    ).then(pl.lit("valid_reptec"))
    
    .when(
        (pl.col("cell_type") == 'HUVEC_TNFalpha') & 
        (pl.col("rec_id").list.set_intersection(huvec_held_out).list.len() > 0)
    ).then(pl.lit("valid_huvec_tnfalpha"))
    
    .otherwise(pl.col("split")) # Preserves existing 'split' value (e.g., 'train')
    .alias("split")
)

In [ ]:
df = df.with_row_index("row_idx") 
bf3_indices = df.filter(pl.col("assay_type") == "brightfield_3channel").select("row_idx")
sampled_bf3_indices = bf3_indices.sample(fraction=0.003, shuffle=True) # just saving approximately 32 000 rows for FID

cp_indices = df.filter(pl.col("assay_type") == "cellpaint").select("row_idx")
sampled_cp_indices = cp_indices.sample(fraction=0.0005, shuffle=True) # just saving approximately 32 000 rows for FID

df = df.with_columns(
    pl.when(pl.col("row_idx").is_in(sampled_bf3_indices["row_idx"]))
      .then(pl.lit("valid_bf3_iid"))
      .when(pl.col("row_idx").is_in(sampled_cp_indices["row_idx"]))
      .then(pl.lit("valid_cp_iid"))
      .otherwise(pl.col("split"))
      .alias("split")
).drop("row_idx") # Clean up the temporary index
df['split'].value_counts()

/tmp/ipykernel_189811/215323776.py:8: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  df = df.with_columns(

shape: (6, 2)
┌──────────────────────┬──────────┐
│ split                ┆ count    │
│ ---                  ┆ ---      │
│ str                  ┆ u32      │
╞══════════════════════╪══════════╡
│ valid_huvec_tnfalpha ┆ 83012    │
│ valid_bf3_iid        ┆ 88023    │
│ valid_arpe19         ┆ 544103   │
│ train                ┆ 95481993 │
│ valid_reptec         ┆ 708996   │
│ valid_cp_iid         ┆ 80175    │
└──────────────────────┴──────────┘

In [18]:
tmp = df.with_columns(
    n_perts = pl.col("rec_id").list.len()
).with_columns(
    is_negative_control = (
        (pl.col("n_perts") == 1) & 
        (pl.col("rec_id").list.set_intersection(NEGATIVE_CONTROLS).list.len() > 0)
    ),
    drugscreen_query = pl.lit(False), # This is wrong, but we're not evaluating drugscreen on this data
    plate_disease_model = pl.lit(None),
    batch_center = pl.struct(["order_id", "read_id", "plate"]).rank("dense") # Note: this won't be distinct from the cross cell line task
).with_columns(
    is_base_state = pl.col('is_negative_control')
)
#tmp # Not used for now - but we should be able to modify this to make RXRX data compatible with VCB

# Cross cell line

In [ ]:
cross_cell_line_df_train: pl.DataFrame = (pl.read_parquet(str(CROSS_CELL_LINE_OBS_PATH)).with_columns(
        pl.lit("brightfield_3channel").alias("assay_type"),
        pl.lit("cross_cell_line").alias("source"),
        pl.lit([2048, 2048, 3]).alias("shape"),
        pl.lit("train").alias("split"),
        rec_id=pl.col("perturbations").list.eval(
            pl.element().struct.field("source_id")
        ),
        concentration=pl.col("perturbations").list.eval(
            pl.element().struct.field("concentration").cast(pl.Float64).cast(pl.String)
        ),
    )
)
cross_cell_line_df_test: pl.DataFrame = (pl.read_parquet(str(CROSS_CELL_LINE_TEST_OBS_PATH)).with_columns(
        pl.lit("brightfield_3channel").alias("assay_type"),
        pl.lit("cross_cell_line").alias("source"),
        pl.lit([2048, 2048, 3]).alias("shape"),
        pl.lit("test").alias("split"),
        rec_id=pl.col("perturbations").list.eval(
            pl.element().struct.field("source_id")
        ),
        concentration=pl.col("perturbations").list.eval(
            pl.element().struct.field("concentration").cast(pl.Float64).cast(pl.String)
        ),
    )
)

cross_cell_line_df: pl.DataFrame = pl.concat([cross_cell_line_df_train, cross_cell_line_df_test[cross_cell_line_df_train.columns]])
print("Cell type diversity data (aka Charles' data)")
rec_id_tokenizer = Tokenizer().fit(cross_cell_line_df['rec_id'].explode().unique())
concentration_tokenizer = Tokenizer().fit(cross_cell_line_df['concentration'].explode().unique())
cell_type_tokenizer = Tokenizer().fit(cross_cell_line_df['cell_type'].unique())
assay_type_tokenizer = Tokenizer().fit(cross_cell_line_df['assay_type'].unique())
experiment_tokenizer = Tokenizer().fit(cross_cell_line_df['experiment_label'].unique())

print("Unique rec_ids: ", len(rec_id_tokenizer))
print("Unique concentrations: ", len(concentration_tokenizer))
print("Unique cell_types: ", len(cell_type_tokenizer))
print("Unique assay_types: ", len(assay_type_tokenizer))
print("Unique experiments: ", len(experiment_tokenizer))

Cell type diversity data (aka Charles' data)
Unique rec_ids:  6655
Unique concentrations:  5
Unique cell_types:  20
Unique image_types:  1
Unique experiments:  198

In [20]:
# 1. Create the consistent string ID
cross_cell_line_df_train = cross_cell_line_df_train.with_columns(
    rec_id_string = pl.col('rec_id').list.sort().list.join('-')
)

sampled_ids = (
    cross_cell_line_df_train.filter(pl.col("cell_type") == "A_704") # use one cell type so the same rec_ids are used everywhere
    .select("rec_id_string")
    .unique(maintain_order=True)
    .sample(n=249, seed=98765, shuffle=True)
)
sampled_ids = pl.concat([sampled_ids, pl.DataFrame({'rec_id_string': ['REC-0000814']})])
sampled_ids.write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/metadata/cross_cell_line_sampled_rec_ids.parquet')

# 3. Assign the split column
# If the ID is in our sampled list, it is 'valid' everywhere it appears.
cross_cell_line_df_train = cross_cell_line_df_train.with_columns(
    pl.when(pl.col("rec_id_string").is_in(sampled_ids.get_column("rec_id_string")))
    .then(pl.lit("valid_cross_cell_line_map"))
    .otherwise(pl.col("split"))
    .alias("split")
)


cross_cell_line_df_test = (cross_cell_line_df_test.with_row_index("row_idx").with_columns(
    rec_id_string = pl.col('rec_id').list.sort().list.join('-'),
    split = pl.when(pl.col("row_idx").is_in(cross_cell_line_splits.finetune))
    .then(pl.lit("train"))
    .when(pl.col("row_idx").is_in(cross_cell_line_splits.validation))
    .then(pl.lit("valid_cross_cell_line"))
    .when(pl.col("row_idx").is_in(cross_cell_line_splits.test))
    .then(pl.lit("test_cross_cell_line"))
    .otherwise(pl.lit("train")))).drop("row_idx")
cross_cell_line_df: pl.DataFrame = pl.concat([cross_cell_line_df_train, cross_cell_line_df_test[cross_cell_line_df_train.columns]])

# 4. Check the results (Stats)
stats = (
    cross_cell_line_df
    .group_by(["cell_type", "split"])
    .agg(
        pl.col("rec_id_string").n_unique().alias("unique_count"),
        pl.len().alias("total_rows")
    )
    .sort(["cell_type", "split"])
)
with pl.Config(tbl_rows=100):
    print(stats)

/tmp/ipykernel_189811/2618045621.py:17: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  cross_cell_line_df_train = cross_cell_line_df_train.with_columns(

shape: (40, 4)
┌─────────────────────┬───────────────────────────┬──────────────┬────────────┐
│ cell_type           ┆ split                     ┆ unique_count ┆ total_rows │
│ ---                 ┆ ---                       ┆ ---          ┆ ---        │
│ str                 ┆ str                       ┆ u32          ┆ u32        │
╞═════════════════════╪═══════════════════════════╪══════════════╪════════════╡
│ AC16                ┆ train                     ┆ 4890         ┆ 74184      │
│ AC16                ┆ valid_cross_cell_line     ┆ 1764         ┆ 14112      │
│ A_704               ┆ train                     ┆ 1286         ┆ 38144      │
│ A_704               ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ BxPC3               ┆ train                     ┆ 1286         ┆ 38144      │
│ BxPC3               ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ HACAT               ┆ train                     ┆ 5126         ┆ 71264      │
│ HACAT               ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ HCT116              ┆ train                     ┆ 1286         ┆ 38144      │
│ HCT116              ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ HEPARG              ┆ train                     ┆ 6404         ┆ 82293      │
│ HEPARG              ┆ valid_cross_cell_line_map ┆ 250          ┆ 6000       │
│ HEPG2               ┆ train                     ┆ 1286         ┆ 29789      │
│ HEPG2               ┆ valid_cross_cell_line_map ┆ 250          ┆ 4696       │
│ HMVECc              ┆ train                     ┆ 1286         ┆ 38144      │
│ HMVECc              ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ HRCE                ┆ train                     ┆ 6405         ┆ 82286      │
│ HRCE                ┆ valid_cross_cell_line_map ┆ 250          ┆ 6000       │
│ HSMM                ┆ train                     ┆ 1286         ┆ 38144      │
│ HSMM                ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ NCI-H1703           ┆ train                     ┆ 1286         ┆ 38145      │
│ NCI-H1703           ┆ valid_cross_cell_line_map ┆ 250          ┆ 5991       │
│ NHBE                ┆ train                     ┆ 1286         ┆ 38144      │
│ NHBE                ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ NHCF-V              ┆ train                     ┆ 1286         ┆ 38144      │
│ NHCF-V              ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ NHEK                ┆ train                     ┆ 4891         ┆ 74184      │
│ NHEK                ┆ valid_cross_cell_line     ┆ 1764         ┆ 14112      │
│ NHLF                ┆ train                     ┆ 1286         ┆ 38144      │
│ NHLF                ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ OV90                ┆ train                     ┆ 1286         ┆ 38144      │
│ OV90                ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ SHSY5Y              ┆ train                     ┆ 1286         ┆ 38144      │
│ SHSY5Y              ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ U2OS                ┆ train                     ┆ 1286         ┆ 38144      │
│ U2OS                ┆ valid_cross_cell_line_map ┆ 250          ┆ 5992       │
│ hMSC                ┆ test_cross_cell_line      ┆ 1516         ┆ 36384      │
│ hMSC                ┆ train                     ┆ 20           ┆ 7752       │
│ iPSC-CARDIOMYOCYTES ┆ train                     ┆ 1286         ┆ 38138      │
│ iPSC-CARDIOMYOCYTES ┆ valid_cross_cell_line_map ┆ 250          ┆ 5998       │
└─────────────────────┴───────────────────────────┴──────────────┴────────────┘

This parquet file (`cross_cell_line_v2.parquet`) is used for finetuning the model for the cross cell type task. Only the training examples are used and it is not used during pretraining.

In [21]:
cross_cell_line_df.write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/joint-model/metadata/cross_cell_line_v2.parquet')

`cross_cell_line_inference.parquet` is where I'll save the parquet file that will be used for running inference with the model. When I originally saved it I forgot to include controls, so I've now also saved `cross_cell_line_controls.parquet`. Code for both is below

In [22]:
exp_controls = []
for cell_type in cross_cell_line_df['cell_type'].unique():
    exp_subset = cross_cell_line_df.filter(
        ((pl.col('split').str.contains('valid_')))
        & (pl.col('cell_type') == cell_type))['experiment_label'].unique()
    exp_controls.append(cross_cell_line_df.filter(
        (pl.col('is_negative_control') ) & 
        (pl.col('cell_type') == cell_type) & 
        (pl.col('experiment_label').is_in(exp_subset)) 
        )
    )
exp_controls = pl.concat(exp_controls)
ccl_inf_parquet = pl.concat([exp_controls, cross_cell_line_df.filter((pl.col('split').str.contains('valid_')))])
ccl_inf_parquet.write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/metadata/cross_cell_line_inference-map.parquet')

/tmp/ipykernel_189811/1646113381.py:6: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  exp_controls.append(cross_cell_line_df.filter(

In [23]:
# | (pl.col('split') == 'test_cross_cell_line')
exp_controls = []
for cell_type in cross_cell_line_df['cell_type'].unique():
    exp_subset = cross_cell_line_df.filter(
        ((pl.col('split') == 'test_cross_cell_line'))
        & (pl.col('cell_type') == cell_type))['experiment_label'].unique()
    exp_controls.append(cross_cell_line_df.filter(
        (pl.col('is_negative_control') ) & 
        (pl.col('cell_type') == cell_type) & 
        (pl.col('experiment_label').is_in(exp_subset)) 
        )
    )
exp_controls = pl.concat(exp_controls)
ccl_inf_parquet = pl.concat([exp_controls, cross_cell_line_df.filter((pl.col('split') == 'test_cross_cell_line'))])
ccl_inf_parquet.write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/metadata/cross_cell_line_inference-test.parquet')

/tmp/ipykernel_189811/3109575418.py:7: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  exp_controls.append(cross_cell_line_df.filter(

# Drugscreen

This is almost exactly the same as the steps above except we use the splits to define train / test / valid.

**Only potential gotcha:** see how I'm adding an id column and check its okay

In [ ]:
drugscreen_obs = pl.read_parquet(str(DRUGSCREEN_OBS_PATH)).with_row_index("id").with_columns(
        pl.lit("cellpaint").alias("assay_type"),
        pl.lit("drugscreen").alias("source"),
        pl.lit([2048, 2048, 6]).alias("shape"),
        split = pl.when(pl.col("id").is_in(vcb_splits.finetune))
        .then(pl.lit("train"))
            .when(pl.col("id").is_in(vcb_splits.validation))
        .then(pl.lit("valid_drugscreen"))
        .when(pl.col("id").is_in(vcb_splits.test))
        .then(pl.lit("test_drugscreen"))
        .otherwise(pl.lit("train")),
        rec_id=pl.col("perturbations").list.eval(
            pl.element().struct.field("source_id")
        ),
        concentration=pl.col("perturbations").list.eval(
            pl.element().struct.field("concentration").cast(pl.Float64).cast(pl.String)
        ),
    )

print("DRUGSCREEN data")
rec_id_tokenizer = Tokenizer().fit(drugscreen_obs['rec_id'].explode().unique())
concentration_tokenizer = Tokenizer().fit(drugscreen_obs['concentration'].explode().unique())
cell_type_tokenizer = Tokenizer().fit(drugscreen_obs['cell_type'].unique())
assay_type_tokenizer = Tokenizer().fit(drugscreen_obs['assay_type'].unique())
experiment_tokenizer = Tokenizer().fit(drugscreen_obs['experiment_label'].unique())

print("Unique rec_ids: ", len(rec_id_tokenizer))
print("Unique concentrations: ", len(concentration_tokenizer))
print("Unique cell_types: ", len(cell_type_tokenizer))
print("Unique assay_types: ", len(assay_type_tokenizer))
print("Unique experiments: ", len(experiment_tokenizer))

DRUGSCREEN data
Unique rec_ids:  2712
Unique concentrations:  22
Unique cell_types:  2
Unique image_types:  1
Unique experiments:  56

In [3]:
drugscreen_obs['split'].value_counts()

shape: (3, 2)
┌──────────────────┬────────┐
│ split            ┆ count  │
│ ---              ┆ ---    │
│ str              ┆ u32    │
╞══════════════════╪════════╡
│ valid_drugscreen ┆ 40546  │
│ train            ┆ 562049 │
│ test_drugscreen  ┆ 71124  │
└──────────────────┴────────┘

In [ ]:
is_valid_or_test = pl.col('split').is_in(['valid_drugscreen', 'test_drugscreen'])
target_experiments = drugscreen_obs.filter(is_valid_or_test)['experiment_label'].unique()
is_target_experiment = pl.col('experiment_label').is_in(target_experiments)
is_base_or_control = pl.col('is_base_state') | pl.col('is_negative_control')
inference_subset = drugscreen_obs.filter((is_target_experiment & is_base_or_control) | is_valid_or_test)
inference_subset.write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/big-img/metadata/drugscreen_inference.parquet')

/tmp/ipykernel_3781853/2896983154.py:5: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  inference_subset = drugscreen_obs.filter((is_target_experiment & is_base_or_control) | is_valid_or_test)

# Active Learning Data

In [ ]:
import zarr
import pickle
import polars as pl

def get_shape(path) -> tuple[int, int, int]:
    if len(path) > 0:
        return tuple(zarr.open(str(path), mode='r').shape)
    else:
        return None

al = pl.read_parquet("/mnt/ps/home/CORP/jason.hartford/pythondev/photosynthetic/notebooks/AL_metadata.parquet")
al = al.with_columns(
    pl.lit("train").alias("split"),
    n_perts = pl.col("rec_id").list.len(),
    rec_id_string = pl.col('rec_id').list.sort().list.join('-'),
    pert_type_string = pl.col("perturbation_type").list.sort().list.join('-')
).with_row_index("row_id")
al = al.with_columns(
        pl.when(pl.col("n_perts") > 1)
        .then(pl.lit("valid_al"))
        .otherwise(pl.lit("train"))
        .alias("split")
    )
pert_types = ["COMPOUND-GUIDE", "COMPOUND-COMPOUND", "GUIDE-GUIDE"]
for pert_type in pert_types:
    train_ids = al.filter((pl.col("n_perts") > 1) & (pl.col("pert_type_string") == pert_type))['rec_id_string'].unique(maintain_order=True).sample(n=250, seed=420, shuffle=True)
    al = al.with_columns(
        pl.when(pl.col("rec_id_string").is_in(train_ids))
        .then(pl.lit("train"))
        .otherwise(pl.col("split"))
        .alias("split")
    )
# see code below for how this was generated
shapes = pickle.load(open("shapes.pkl", "rb"))
al = al.with_columns(
    shape = pl.Series(shapes)
)

al = al.filter(pl.col("shape") == [2048, 2048, 3]).with_columns(
    pl.lit("brightfield_3channel").alias("assay_type"),
    pl.lit("active_learning").alias("source"),
    concentration = (pl.col("concentration") * 1000).list.eval(
        pl.element().cast(pl.String),
    )
).rename({
    "path": "image_path",
    "experiment": "experiment_label",
    "address": "well_address"
}).with_columns(
    pl.concat_str(['plate', 'order_id' ,'read_id'], separator='_').alias('plate_order_read_id'),
)

stats = (
    al
    .group_by(["n_perts", "pert_type_string", "split"])
    .agg(
        pl.col("rec_id_string").n_unique().alias("unique_count"),
        pl.len().alias("total_rows")
    )
    .sort(["n_perts", "pert_type_string", "split"])
)
with pl.Config(tbl_rows=100):
    print(stats)

/tmp/ipykernel_189811/2957958617.py:27: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  al = al.with_columns(

shape: (9, 5)
┌─────────┬───────────────────┬──────────┬──────────────┬────────────┐
│ n_perts ┆ pert_type_string  ┆ split    ┆ unique_count ┆ total_rows │
│ ---     ┆ ---               ┆ ---      ┆ ---          ┆ ---        │
│ u32     ┆ str               ┆ str      ┆ u32          ┆ u32        │
╞═════════╪═══════════════════╪══════════╪══════════════╪════════════╡
│ 0       ┆                   ┆ train    ┆ 1            ┆ 86098      │
│ 1       ┆ COMPOUND          ┆ train    ┆ 50           ┆ 10801      │
│ 1       ┆ GUIDE             ┆ train    ┆ 1421         ┆ 112863     │
│ 2       ┆ COMPOUND-COMPOUND ┆ train    ┆ 250          ┆ 16352      │
│ 2       ┆ COMPOUND-COMPOUND ┆ valid_al ┆ 1025         ┆ 67480      │
│ 2       ┆ COMPOUND-GUIDE    ┆ train    ┆ 222          ┆ 5329       │
│ 2       ┆ COMPOUND-GUIDE    ┆ valid_al ┆ 7278         ┆ 174610     │
│ 2       ┆ GUIDE-GUIDE       ┆ train    ┆ 227          ┆ 2522       │
│ 2       ┆ GUIDE-GUIDE       ┆ valid_al ┆ 47526        ┆ 534226     │
└─────────┴───────────────────┴──────────┴──────────────┴────────────┘

In [27]:
# import pickle
# shapes = []
# for i in tqdm.tqdm(range(al.shape[0])):
#     try:
#         shapes.append(get_shape(al[i]["path"][0]))
#     except Exception as e:
#         print(e)
#         shapes.append(None)
# pickle.dump(shapes, open("shapes.pkl", "wb"))

#al.write_parquet("/mnt/ps/home/CORP/jason.hartford/pythondev/photosynthetic/notebooks/AL_metadata.parquet")

# Now lets merge it all together

In [28]:
df = df.with_columns(
    pl.concat_str(['plate', 'order_id' ,'read_id'], separator='_').alias('plate_order_read_id'),
    pl.lit("pretraining").alias("source"),
    concentration=pl.col('concentration').list.eval(
    pl.element().cast(pl.String),
))
cols = sorted(list(set(df.columns).intersection(set(drugscreen_obs.columns))))
combined = pl.concat([df[cols], drugscreen_obs[cols], cross_cell_line_df[cols], al[cols]])
combined = combined.filter(~pl.col("image_path").is_in(SKIP_IMAGES)) # skip images that are known to be corrupted

In [29]:
combined.with_columns(pl.concat_str(['plate_order_read_id', 'well_address'], separator=':').alias('obs_id')).write_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/joint-model/metadata/pretraining_v6.parquet')

In [30]:
combined['split'].value_counts()

shape: (12, 2)
┌───────────────────────────┬──────────┐
│ split                     ┆ count    │
│ ---                       ┆ ---      │
│ str                       ┆ u32      │
╞═══════════════════════════╪══════════╡
│ valid_bf3_iid             ┆ 88023    │
│ valid_cross_cell_line_map ┆ 100589   │
│ valid_al                  ┆ 776316   │
│ valid_cross_cell_line     ┆ 28224    │
│ valid_cp_iid              ┆ 80175    │
│ …                         ┆ …        │
│ train                     ┆ 97195555 │
│ valid_huvec_tnfalpha      ┆ 83012    │
│ valid_reptec              ┆ 708996   │
│ test_cross_cell_line      ┆ 36384    │
│ valid_arpe19              ┆ 544103   │
└───────────────────────────┴──────────┘

In [23]:
print(combined['rec_id'].explode().unique().shape)
combined.with_columns(rec_id_str = pl.col('rec_id').list.sort().list.join('-'))['rec_id_str'].unique().shape

(628692,)

(1568513,)

In [24]:
rec_ids = combined['rec_id'].explode().unique()

In [25]:
from collections import Counter
out = Counter([tuple(i.split('-')[:-1]) for i in rec_ids if i is not None])
out

Counter({('REC',): 492792,
         ('REC', 'GRNA'): 115232,
         ('REC', 'SIRNA'): 19822,
         ('REC', 'SF'): 584,
         ('REC', 'ANTIBODY'): 121,
         ('REC', 'SGRNA'): 50,
         ('REC', 'VIRUS'): 45,
         ('REC', 'APTAMER'): 23,
         ('REC', 'MC'): 14,
         ('REC', 'MRNA'): 6,
         ('REC', 'PBS'): 1,
         ('REC', 'PBS', 'BSA'): 1})

In [26]:
with pl.Config(tbl_rows=100):
    print(combined['split'].value_counts())

shape: (12, 2)
┌───────────────────────────┬──────────┐
│ split                     ┆ count    │
│ ---                       ┆ ---      │
│ str                       ┆ u32      │
╞═══════════════════════════╪══════════╡
│ valid_arpe19              ┆ 544122   │
│ valid_drugscreen          ┆ 40544    │
│ valid_huvec_tnfalpha      ┆ 83001    │
│ test_drugscreen           ┆ 71116    │
│ valid_reptec              ┆ 708978   │
│ valid_cross_cell_line_map ┆ 100583   │
│ valid_al                  ┆ 776316   │
│ test_cross_cell_line      ┆ 36384    │
│ valid_cross_cell_line     ┆ 28224    │
│ valid_cp_iid              ┆ 40228    │
│ train                     ┆ 97242113 │
│ valid_bf3_iid             ┆ 45190    │
└───────────────────────────┴──────────┘

In [ ]:
print("Combined data")
rec_id_tokenizer = Tokenizer().fit(combined['rec_id'].explode().unique())
concentration_tokenizer = Tokenizer().fit(combined['concentration'].explode().unique())
cell_type_tokenizer = Tokenizer().fit(combined['cell_type'].unique())
assay_type_tokenizer = Tokenizer().fit(combined['assay_type'].unique())
experiment_tokenizer = Tokenizer().fit(combined['experiment_label'].unique())
well_tokenizer = Tokenizer().fit(combined['well_address'].unique())

print("Unique rec_ids: ", len(rec_id_tokenizer))
print("Unique concentrations: ", len(concentration_tokenizer))
print("Unique cell_types: ", len(cell_type_tokenizer))
print("Unique assay_types: ", len(assay_type_tokenizer))
print("Unique experiments: ", len(experiment_tokenizer))
print("Unique well_addresses: ", len(well_tokenizer))

Combined data

Unique rec_ids:  628698
Unique concentrations:  386
Unique cell_types:  47
Unique image_types:  4
Unique experiments:  10112
Unique well_addresses:  1531

In [2]:
import polars as pl
combined = pl.read_parquet('/mnt/ps/home/CORP/jason.hartford/project/big-x/joint-model/metadata/pretraining_v6.parquet')

In [ ]:
test = combined[:, ['rec_id', 'concentration', 'cell_type', 'assay_type', 'experiment_label', 'well_address','image_path']]

:

In [ ]:
import time
import numpy as np

start = time.time()
for i in range(10000):
    i = np.random.randint(0, test.shape[0])
    row = test[i, :]
print(time.time() - start)

1.5681843757629395

In [ ]:
start = time.time()
for i in range(10000):
    i = np.random.randint(0, test.shape[0])
    row = test.row(i, named=True)
print(time.time() - start)

1.2902047634124756

In [76]:
start = time.time()
for i in range(10000):
    i = np.random.randint(0, combined.shape[0])
    row = combined.row(i, named=True)
print(time.time() - start)

2.5470874309539795

In [ ]:
test = combined.with_columns(rec_id_str = pl.col('rec_id').list.join('/'), 
conc_str = pl.col('concentration').list.join('/'))[:, ['rec_id_str', 'conc_str', 'cell_type', 'assay_type', 'experiment_label', 'well_address','image_path']]

In [ ]:
i = -2
test.row(i, named=True)['rec_id_str'].split('/') == combined.row(i, named=True)['rec_id'], test.row(i, named=True)['rec_id_str'].split('/')

(True, ['REC-GRNA-0082230', 'REC-GRNA-0141463'])

In [115]:
test

shape: (99_753_037, 7)
┌──────────────┬───────────┬───────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ rec_id_str   ┆ conc_str  ┆ cell_type ┆ image_type   ┆ experiment_l ┆ well_address ┆ image_path   │
│ ---          ┆ ---       ┆ ---       ┆ ---          ┆ abel         ┆ ---          ┆ ---          │
│ str          ┆ str       ┆ str       ┆ str          ┆ ---          ┆ str          ┆ str          │
│              ┆           ┆           ┆              ┆ str          ┆              ┆              │
╞══════════════╪═══════════╪═══════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ REC-GRNA-011 ┆ 100.0     ┆ HUVEC     ┆ brightfield_ ┆ pheno-WholeG ┆ AA02         ┆ /rxrx/data/m │
│ 8831         ┆           ┆           ┆ 3channel     ┆ enome_p1-H-a ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆              ┆              ┆ rr_512…      │
│ REC-GRNA-011 ┆ 100.0     ┆ HUVEC     ┆ brightfield_ ┆ pheno-WholeG ┆ AA03         ┆ /rxrx/data/m │
│ 9199         ┆           ┆           ┆ 3channel     ┆ enome_p1-H-a ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆              ┆              ┆ rr_512…      │
│ REC-GRNA-000 ┆ 100.0     ┆ HUVEC     ┆ brightfield_ ┆ pheno-WholeG ┆ AA04         ┆ /rxrx/data/m │
│ 7820         ┆           ┆           ┆ 3channel     ┆ enome_p1-H-a ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆              ┆              ┆ rr_512…      │
│ REC-GRNA-011 ┆ 100.0     ┆ HUVEC     ┆ brightfield_ ┆ pheno-WholeG ┆ AA05         ┆ /rxrx/data/m │
│ 8019         ┆           ┆           ┆ 3channel     ┆ enome_p1-H-a ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆              ┆              ┆ rr_512…      │
│ REC-GRNA-011 ┆ 100.0     ┆ HUVEC     ┆ brightfield_ ┆ pheno-WholeG ┆ AA06         ┆ /rxrx/data/m │
│ 7128         ┆           ┆           ┆ 3channel     ┆ enome_p1-H-a ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆              ┆              ┆ rr_512…      │
│ …            ┆ …         ┆ …         ┆ …            ┆ …            ┆ …            ┆ …            │
│ REC-GRNA-013 ┆ 100.0     ┆ HUVEC     ┆ brightfield_ ┆ AL001-pheno- ┆ K02          ┆ /rxrx/data/m │
│ 9827         ┆           ┆           ┆ 3channel     ┆ multipert_p3 ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆ 6-H-a        ┆              ┆ rr_512…      │
│              ┆           ┆ HUVEC     ┆ brightfield_ ┆ AL001-pheno- ┆ K03          ┆ /rxrx/data/m │
│              ┆           ┆           ┆ 3channel     ┆ multipert_p3 ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆ 6-H-a        ┆              ┆ rr_512…      │
│              ┆           ┆ HUVEC     ┆ brightfield_ ┆ AL001-pheno- ┆ K04          ┆ /rxrx/data/m │
│              ┆           ┆           ┆ 3channel     ┆ multipert_p3 ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆ 6-H-a        ┆              ┆ rr_512…      │
│ REC-GRNA-008 ┆ 50.0/50.0 ┆ HUVEC     ┆ brightfield_ ┆ AL001-pheno- ┆ K05          ┆ /rxrx/data/m │
│ 2230/REC-GRN ┆           ┆           ┆ 3channel     ┆ multipert_p3 ┆              ┆ icroscopy/za │
│ A-0141…      ┆           ┆           ┆              ┆ 6-H-a        ┆              ┆ rr_512…      │
│              ┆           ┆ HUVEC     ┆ brightfield_ ┆ AL001-pheno- ┆ K06          ┆ /rxrx/data/m │
│              ┆           ┆           ┆ 3channel     ┆ multipert_p3 ┆              ┆ icroscopy/za │
│              ┆           ┆           ┆              ┆ 6-H-a        ┆              ┆ rr_512…      │
└──────────────┴───────────┴───────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [ ]:
start = time.time()
for i in range(10000):
    i = np.random.randint(0, test.shape[0])
    row = test.row(i, named=True)
    rec_id = row['rec_id_str'].split('/')
    conc = row['conc_str'].split('/')
print(time.time() - start)

NameError: name 'time' is not defined